version: '3'

services:
  test:
    image: node:8.15.1
    command: bash -c 'while !</dev/tcp/dbTest/5432; do sleep 1; done; npm run test-watch'
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 4000
    depends_on:
      - dbTest
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: api-test.localtest.me
      VIRTUAL_PORT: 4000
      DB_CONN_DATABASE: api-test-db
      DB_CONN_HOST: dbTest
      DB_CONN_PASSWORD: password
      DB_CONN_PORT: 5432
      DB_CONN_USER: user
      DATABASE_POOL_MIN: 0
      DATABASE_POOL_MAX: 10

  dbTest:
    image: postgres:10.4
    ports:
      - 5432
    command: postgres -D /run/pgsql-10.4-data -F
    environment:
      LOGGING_COLLECTOR: 'on'
      PGDATA: /run/pgsql-10.4-data
      POSTGRES_DB: api-test-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
