version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0
      - image: postgres:10.4
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: api-db

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1

      - run:
          name: Install packages
          command: |
            cd api
            npm i

      - run:
          name: Run unit tests
          environment:
            NODE_ENV: test
            DATABASE_URL: 'postgres://ubuntu@localhost:5432/api-db?sslmode=disable'
          command: |
            cd api
            set -ou pipefail
            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
            # without this option script will return success regardless of testing result due to pipe after test command
            npm run test

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
