version: '3'

services:
  api:
    image: node:8.11.3
    command: npm run dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      DB_CONN_DATABASE: api-db
      DB_CONN_HOST: db
      DB_CONN_PASSWORD: password
      DB_CONN_PORT: 5432
      DB_CONN_USER: user
      GOOGLE_ID: YOUR_APP_GOOGLE_ID
      GOOGLE_SECRET: YOUR_APP_GOOGLE_SECRET
      GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/callback
      LINKEDIN_ID: YOUR_APP_LINKEDIN_ID
      LINKEDIN_SECRET: YOUR_APP_LINKEDIN_SECRET
      LINKEDIN_CALLBACK_URL: http://localhost:3001/api/auth/linkedin/callback
      FACEBOOK_ID: YOUR_APP_FACEBOOK_ID
      FACEBOOK_SECRET: YOUR_APP_FACEBOOK_SECRET
      FACEBOOK_CALLBACK_URL: http://localhost:3001/api/auth/facebook/callback
      SUCCESS_LOGIN_REDIRECT_URL: http://localhost:3001/api/
      NODE_ENV: development
      DATABASE_POOL_MIN: 0
      DATABASE_POOL_MAX: 10
      ENABLE_NODE_CLUSTER: 'false'
  db:
    image: postgres:10.4
    ports:
      - 5432:5432
    command: postgres -D /run/pgsql-10.4-data -c logging_collector=on
    volumes:
      - ./db/local_database_volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      LOGGING_COLLECTOR: 'on'
      PGDATA: /run/pgsql-10.4-data
      POSTGRES_DB: api-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
