version: '3'

services:
  test:
    image: node:8.11.3
    command: npm run test
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - dbTest
    environment:
      DB_CONN_DATABASE: api-test-db
      DB_CONN_HOST: dbTest
      DB_CONN_PASSWORD: password
      DB_CONN_PORT: 5432
      DB_CONN_USER: user
      LINKEDIN_ID: 77gy1y1ddffvxw
      LINKEDIN_SECRET: WNOSE0fM0KdVPlDq
      LINKEDIN_CALLBACK_URL: http://localhost:3000/auth/linkedin/callback
      NODE_ENV: test
      DATABASE_POOL_MIN: 0
      DATABASE_POOL_MAX: 10
  dbTest:
    image: postgres:10.4
    ports:
      - 5432
    command: postgres -D /run/pgsql-10.4-data -F
    environment:
      LOGGING_COLLECTOR: 'on'
      PGDATA: /run/pgsql-10.4-data
      POSTGRES_DB: api-test-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
